name: Push on commit

push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Send Push Notification
      uses: techulus/push-github-action@1.0.0
      env:
        API_KEY: ${{ secrets.API_KEY }}
        MESSAGE: "Hey Ausawin, there's a new build"
